
Log:
  Level: warning
  AccessPath:
  ErrorPath:
DnsConfigPath:
InboundConfigPath:
RouteConfigPath: /etc/XrayR/route.json
OutboundConfigPath: /etc/XrayR/custom_outbound.json
ConnetionConfig:
  Handshake: 4
  ConnIdle: 30
  UplinkOnly: 2
  DownlinkOnly: 4
  BufferSize: 64
Nodes:

- PanelType: "V2board"
  ApiConfig:
    ApiHost: "https://a2.lion688.com"
    ApiKey: "useramehbzlxhramea"
    NodeID: 5
    NodeType: V2ray
    Timeout: 30
    EnableVless: false
    EnableXTLS: false
    SpeedLimit: 0
    DeviceLimit: 0
  ControllerConfig:
    ListenIP: 0.0.0.0
    SendIP: 0.0.0.0
    UpdatePeriodic: 60
    EnableDNS: false
    DNSType: AsIs
    EnableProxyProtocol: false
